name: weather_app
description: "A simple flutter weather app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  modal_bottom_sheet: ^3.0.0
  intl: ^0.19.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  image_path: "assets/moderateorheavyrainshower.png"
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/
